### ISSUE TITLE
X32CustomLayer - incorrect preamp settings

### ISSUE THREAD

**Issue by szkudlik** [pmaillot/X32-Behringer#15]
Hi, 

I'd like to report a defect in x32CustomLayer app

Problem is here:
			LoadCStrip(k, i);    <<<< first load all data from the second channel, INCLUDING preamp settings
			SetASource(i, Asrc[k - 1]);  <<<< than change the source

Problem is that loading the channel appies also preamp settings, the settigs are applied BEFORE the source has been changed, so in fact are applied to incorrect preamp. 
In result the mix is destroyed after using the app

As the app is design to change the order of the channels only, not changing the ways that the sources are physically connected, it should never change setting of any preamp. The fix is really simple, just filter out preamp settings when applying the saved channel  by changing insertion mask from 63 to 62

`
 X32CustomLayer.c

line 121:
	int LibRecallMask= 62;        // mask value for X32 /load and /save command

line 1123:
	s_len = Xsprint(s_buf, s_len, 'i', &LibRecallMask);

**Comment by pmaillot** [comment]
Fix accepted and applied. Thanks for your contribution!
Rgds
