### ISSUE TITLE
File name handling bug

### ISSUE THREAD

**Issue by mpvano** [pmaillot/X32-Behringer#16]
Hi!

I'd actually prefer to bring this up in the Behringer forum, since it affects a lot of users who aren't likely to chase down your github. Of course, that forum is now completely useless!

It would be great if you could figure a way to  let users there know that they should workaround the problem until it can be fixed.

It's too bad that the new forum's designers seem to have missed the point of having a forum!

In any case:

I'm seeing a consistent error in the Macintosh version (at least) of X32Xlive_Wav where if a command line like:

     ~/bin/X32mac/X32Xlive_Wav  -n 32 -c 24  ../4E57ABA4/

is used to burst all files to 24 bit and place the results into the current directory, the resulting file names are all prepended with a '.' and become invisible!

Using the '-d .' option solves the problem, but the default for '-d' appears to be broken.

This is a bit confusing, of course, since the files are all created, but don't show up in the finder or in a normal ls command.

thanks again for a great utility and all your work.

**Comment by pmaillot** [comment]
Hello

Thanks a lot!  There's indeed a bug (I just forgot to give a default value
to the output directory, oops!).

Fixed it in the latest version (0.36) which I just uploaded.
I'll tell the forum users as well.

Thanks again,
-Patrick

**Comment by mpvano** [comment]
Thanks, I noticed it a while ago but forgot to report it.

M
