### ISSUE TITLE
GUESTION: Automated fade for channels

### ISSUE THREAD

**Issue by jeremiasmanninen** [pmaillot/X32-Behringer#21]
Hello there!

I have been looking at your X32 OSC protocol and thank you very much for sharing it; it is awesome! 😄 

I was wondering if what would be the easiest way to create an automated fade with a single OSC message. I'm using osculator so it can be routed as sending multiple different messages when receiving one message. I was thinking if there would be any easier than the manual entering all the values and delays. Would some of the apps you have build or anything else work for that? 

Great would also be to get a situation for a fade from the current dB value to a specified dB value. 

Best regards,
Jeremias Manninen, from Finland

**Comment by pmaillot** [comment]
Hello Jeremias,

 

I wrote a program sometime back to manage fades on an X32. I just added it back to the website ( look for X32fade).

 

I know Paul Vannatto also wrote a series of utilities for X32, and some of them provide or include fader timed moves such as used in fading effects. You may want ot look for options there too as Paul wrote some really good apps.

 

Hope this helps,

BR,

-Patrick

 

From: jeremiasmanninen ***@***.***> 
Sent: Friday, May 21, 2021 7:30 PM
To: pmaillot/X32-Behringer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pmaillot/X32-Behringer] GUESTION: Automated fade for channels (#21)

 

Hello there!

I have been looking at your X32 OSC protocol and thank you very much for sharing it; it is awesome! 😄

I was wondering if what would be the easiest way to create an automated fade with a single OSC message. I'm using osculator so it can be routed as sending multiple different messages when receiving one message. I was thinking if there would be any easier than the manual entering all the values and delays. Would some of the apps you have build or anything else work for that?

Great would also be to get a situation for a fade from the current dB value to a specified dB value.

Best regards,
Jeremias Manninen, from Finland
