### ISSUE TITLE
X32 Emulator MacOS not working

### ISSUE THREAD

**Issue by noahdennis-sys** [pmaillot/X32-Behringer#22]
I'm not sure if I'm not understanding something, but I keep getting an error of `X32 resource file does not exist, create one with '/shutdown' command` which isn't going away. 

I have tried running the /shutdown command but it hasn't done anything, so I'm not sure how to fix it.

I'm running it from ./X32 -i 192.168.0.18 

And the ip is my machines ip

**Comment by pmaillot** [comment]
Hello,

 

You need to run X32, and then from a tool such as X32_Command, you send the /shutdown command to the emulator. This will create a resource file.

 

-P

 

From: Noah Dennis ***@***.***> 
Sent: Monday, March 21, 2022 11:39 PM
To: pmaillot/X32-Behringer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pmaillot/X32-Behringer] X32 Emulator MacOS not working (Issue #22)

 

I'm not sure if I'm not understanding something, but I keep getting an error of X32 resource file does not exist, create one with '/shutdown' command which isn't going away.

I have tried running the /shutdown command but it hasn't done anything, so I'm not sure how to fix it.

I'm running it from ./X32 -i 192.168.0.18

And the ip is my machines ip
