### ISSUE TITLE
X32 sim process remains active when quitting terminal first

### ISSUE THREAD

**Issue by ljvdhooft** [pmaillot/X32-Behringer#24]
Process remains active if the terminal is quit without stopping the process. When the X32 sim is opened again the virtual console cannot be initialised since the ip:port is already in use. Full machine restart is required to fix this

**Comment by pmaillot** [comment]
Give more detail on what you did to come to that situation. I have launched X32, then an app that connected to it. while the app was running and still connected, I killed the terminal window of X32 emulator, and relaunched a new one with X32 emulator in it. No issues.

**Comment by ljvdhooft** [comment]
When the terminal is killed with the X32 emulator still running I get the following message when I try to restart the emulator on the previous IP address (blurred out):
Error on IP address: x.x.x.x - cannot run

Running netstat reveals the IP address with :10023 as a running process.

(MacBook Pro 2021, MacOS 12.3 Monterey)

**Comment by pmaillot** [comment]
Probably a Mac thing. Just ensure you kill the X32 process then. Or update the code to ensure the process kills itself when exiting the Mac terminal with the program still running.
