### ISSUE TITLE
Emulator crashes when changing FX to delay-type in offline editor

### ISSUE THREAD

**Issue by ljvdhooft** [pmaillot/X32-Behringer#25]
The emulator (windows version) crashes when the type of a FX slot is changed to a delay-type FX (10, 11, 12, 21, 24, 25).

**Steps to reproduce:**
- Start the X32 emulator, then connect the X32 EDIT offline editor and sync Mixer > PC.
- Change any FX slot 1-4 to a delay-type fx.

**Expected result:**
The OSC calls are responded correctly and the emulator continues listening.

**Actual result:**
The last request made by X32 EDIT is /node fx/[%]/par which is not responded.
then, the emulator crashes.

**Comment by pmaillot** [comment]
Just tested with the latest versions of both emulator and x32-edit. Didn't see the issue. No crash after setting the first 3 FX to delay types: Here's a dump of the OSC exchanges:
->X,   24 B: /node~~~,s~~headamp/126~
X->,   36 B: node~~~~,s~~/headamp/126 -12.0 OFF~~
->X,   24 B: /node~~~,s~~headamp/127~
X->,   36 B: node~~~~,s~~/headamp/127 -12.0 OFF~~
->X,   24 B: /node~~~,s~~-prefs/card~
X->,   64 B: node~~~~,s~~/-prefs/card FW 32/32 32/32 IN WC 56 1-32 OFF OFF~~~
->X,   16 B: /showdump~~~,~~~
X->,   64 B: node~~~~,s~~/-show/showfile/show "" 0 0 0 0 0 0 0 0 0 0 "4.06"~~
->X,   36 B: /-show/showfile/show/name~~~,s~~~~~~
->X,   24 B: /-stat/keysolo~~,i~~[     0]
->X,   20 B: /fx/1/type~~,i~~[    10]
->X,   24 B: /node~~~,s~~fx/1/par~~~~
X->,   72 B: node~~~~,s~~/fx/1/par 0 1 ST 1/4 1/4 -100 10.0 200.0 10.0 1 1 200.0~~~~~
->X,   24 B: /fx/1/par/01~~~~,f~~[0.0000]
->X,   24 B: /fx/1/par/02~~~~,f~~[0.0000]
->X,   24 B: /fx/1/par/03~~~~,i~~[     0]
->X,   24 B: /fx/1/par/04~~~~,i~~[     0]
->X,   24 B: /fx/1/par/05~~~~,i~~[     0]
->X,   24 B: /fx/1/par/06~~~~,f~~[0.0000]
->X,   24 B: /fx/1/par/07~~~~,f~~[0.0000]
->X,   24 B: /fx/1/par/08~~~~,f~~[0.0000]
->X,   24 B: /fx/1/par/09~~~~,f~~[0.0000]
->X,   24 B: /fx/1/par/10~~~~,f~~[0.0200]
->X,   24 B: /fx/1/par/11~~~~,f~~[0.0200]
->X,   24 B: /fx/1/par/12~~~~,f~~[0.0000]
->X,   24 B: /fx/1/par/01~~~~,f~~[0.0200]
->X,   24 B: /fx/1/par/01~~~~,f~~[0.0400]
->X,   24 B: /fx/1/par/01~~~~,f~~[0.0600]
->X,   24 B: /fx/1/par/01~~~~,f~~[0.0800]
->X,   24 B: /fx/1/par/01~~~~,f~~[0.1000]
->X,   24 B: /fx/1/par/01~~~~,f~~[0.1200]
->X,   24 B: /fx/1/par/07~~~~,f~~[0.0200]
->X,   24 B: /fx/1/par/07~~~~,f~~[0.0400]
->X,   24 B: /fx/1/par/07~~~~,f~~[0.0200]
->X,   24 B: /fx/1/par/07~~~~,f~~[0.0400]
->X,   24 B: /fx/1/par/07~~~~,f~~[0.0600]
->X,   24 B: /fx/1/par/07~~~~,f~~[0.0800]
->X,   24 B: /fx/1/par/07~~~~,f~~[0.1000]
->X,   20 B: /fx/2/type~~,i~~[    11]
->X,   24 B: /node~~~,s~~fx/2/par~~~~
X->,   80 B: node~~~~,s~~/fx/2/par 1 0 -100 0 10.0 200.0 1/4 0 -100 1/4 0 -100 OFF OFF OFF~~~
->X,   24 B: /fx/2/par/01~~~~,f~~[0.0000]
->X,   24 B: /fx/2/par/02~~~~,f~~[0.0000]
->X,   24 B: /fx/2/par/03~~~~,f~~[0.0000]
->X,   24 B: /fx/2/par/04~~~~,f~~[0.0000]
->X,   24 B: /fx/2/par/05~~~~,f~~[0.0000]
->X,   24 B: /fx/2/par/06~~~~,f~~[0.0000]
->X,   24 B: /fx/2/par/07~~~~,i~~[     0]
->X,   24 B: /fx/2/par/08~~~~,f~~[0.0000]
->X,   24 B: /fx/2/par/09~~~~,f~~[0.0000]
->X,   24 B: /fx/2/par/10~~~~,i~~[     0]
->X,   24 B: /fx/2/par/11~~~~,f~~[0.0000]
->X,   24 B: /fx/2/par/12~~~~,f~~[0.0000]
->X,   24 B: /fx/2/par/13~~~~,i~~[     0]
->X,   24 B: /fx/2/par/14~~~~,i~~[     0]
->X,   24 B: /fx/2/par/15~~~~,i~~[     0]
->X,   24 B: /fx/2/par/01~~~~,f~~[0.0040]
->X,   24 B: /fx/2/par/01~~~~,f~~[0.0080]
->X,   24 B: /fx/2/par/01~~~~,f~~[0.0120]
->X,   24 B: /fx/2/par/01~~~~,f~~[0.0160]
->X,   24 B: /fx/2/par/01~~~~,f~~[0.0240]
->X,   24 B: /fx/2/par/01~~~~,f~~[0.0280]
->X,   24 B: /fx/2/par/01~~~~,f~~[0.0320]
->X,   24 B: /fx/2/par/01~~~~,f~~[0.0400]
->X,   24 B: /fx/2/par/01~~~~,f~~[0.0440]
->X,   24 B: /fx/2/par/01~~~~,f~~[0.0480]
->X,   24 B: /fx/2/par/01~~~~,f~~[0.0520]
->X,   24 B: /fx/2/par/01~~~~,f~~[0.0600]
->X,   24 B: /fx/2/par/01~~~~,f~~[0.0680]
->X,   24 B: /fx/2/par/01~~~~,f~~[0.0720]
->X,   24 B: /fx/2/par/01~~~~,f~~[0.0760]
->X,   24 B: /fx/2/par/01~~~~,f~~[0.0800]
->X,   24 B: /fx/2/par/01~~~~,f~~[0.0840]
->X,   24 B: /fx/2/par/01~~~~,f~~[0.0880]
->X,   24 B: /fx/2/par/01~~~~,f~~[0.0920]
->X,   24 B: /fx/2/par/01~~~~,f~~[0.0960]
->X,   24 B: /fx/2/par/01~~~~,f~~[0.1040]
->X,   24 B: /fx/2/par/04~~~~,f~~[0.0200]
->X,   24 B: /fx/2/par/04~~~~,f~~[0.0400]
->X,   24 B: /fx/2/par/04~~~~,f~~[0.0600]
->X,   20 B: /fx/3/type~~,i~~[    12]
->X,   24 B: /node~~~,s~~fx/3/par~~~~
X->,   72 B: node~~~~,s~~/fx/3/par 1 0 0 10.0 200.0 0 1/4 0 1/4 0 1/4 0 OFF OFF OFF~~
->X,   24 B: /fx/3/par/01~~~~,f~~[0.0000]
->X,   24 B: /fx/3/par/02~~~~,f~~[0.0000]
->X,   24 B: /fx/3/par/03~~~~,f~~[0.0000]
->X,   24 B: /fx/3/par/04~~~~,f~~[0.0000]
->X,   24 B: /fx/3/par/05~~~~,f~~[0.0000]
->X,   24 B: /fx/3/par/06~~~~,f~~[0.0000]
->X,   24 B: /fx/3/par/07~~~~,i~~[     0]
->X,   24 B: /fx/3/par/08~~~~,f~~[0.0000]
->X,   24 B: /fx/3/par/09~~~~,i~~[     0]
->X,   24 B: /fx/3/par/10~~~~,f~~[0.0000]
->X,   24 B: /fx/3/par/11~~~~,i~~[     0]
->X,   24 B: /fx/3/par/12~~~~,f~~[0.0000]
->X,   24 B: /fx/3/par/13~~~~,i~~[     0]
->X,   24 B: /fx/3/par/14~~~~,i~~[     0]
->X,   24 B: /fx/3/par/15~~~~,i~~[     0]
->X,   24 B: /fx/3/par/06~~~~,f~~[0.1667]
->X,   24 B: /fx/3/par/04~~~~,f~~[0.0200]
->X,   24 B: /fx/3/par/04~~~~,f~~[0.0400]
->X,   24 B: /fx/3/par/04~~~~,f~~[0.0600]
->X,   24 B: /fx/3/par/12~~~~,f~~[0.0200]
->X,   24 B: /fx/3/par/12~~~~,f~~[0.0400]
->X,   24 B: /fx/3/par/12~~~~,f~~[0.0200]
->X,   24 B: /fx/3/par/12~~~~,f~~[0.0400]
->X,   20 B: /unsubscribe~~~~,~~~

**Comment by ljvdhooft** [comment]
Hi Patrick,

I was using the UNIX version on Windows. When I downloaded the compiled Windows executable (X32.exe), it works just fine.

Thanks!
