### ISSUE TITLE
Missing comma, probably a bug

### ISSUE THREAD

**Issue by woolie** [pmaillot/X32-Behringer#29]
Line 386 of X32.c is missing a `,` between " Linear" and " Live", probably creating one string " Linear Live" and probably causing a bug.

```char*   XiQeq[] = {" Linear" " Live", " Speech", " Playback", " User", ""};```

**Comment by pmaillot** [comment]
Yes, obviously a missing comma :)

**Comment by woolie** [comment]
I hope in some small way that helps fix a bug.

**Comment by pmaillot** [comment]
Thanks Steven, it sure helps others, on top of myself.

-Patrick

Le sam. 1 oct. 2022 à 22:48, Steven Woolgar ***@***.***> a
écrit :
