### ISSUE TITLE
XR18_Command Can't connect to XR18

### ISSUE THREAD

**Issue by kmitch95120** [pmaillot/X32-Behringer#3]
The program just spins while trying to connect to XR18. 
A sniffer trace shows a continuous stream of /xinfo commands each followed by a response from the XR18.  See below: 

 XR18_Command - v1.32 - (c)2014-15 Patrick-Gilles Maillot

Connecting to XR18............................................................................................................................................................................................................................................................................................................................................^C

From looking at the code the problem is with lines 276 and 285. On line 276 the initial command is set to "/xinfo" but on line 285 the response is checked for "/info". 

Below is the proposed fix: 
<code>
285c285
<             if (strcmp(r_buf, "/info") == 0)
---
>             if (strcmp(r_buf, "/xinfo") == 0)
</code>
Ken

**Comment by pmaillot** [comment]
Huhooo…. Thanks!

I’ll fix this right away!

**Comment by pmaillot** [comment]
OK fixed! Thanks a lot!
