### ISSUE TITLE
Can't compile apps other than X32_command

### ISSUE THREAD

**Issue by rurubell** [pmaillot/X32-Behringer#30]
Hi and sorry for my English

When I try to compile apps, just like X32GetScene, I always get's errors that gcc can't find x32 libs, can't find functions like "Xsprint()" and another from X32lib folder. I build the object files from X32lib folder, but make still can't find them. Maybe I need to change something in make file?

After all I rename all X32lib files as headers and include everethyng till Make can't show any error. Now I can run X32GetScene, but he is works a little strange. He run 100 ~ 500 lines from reference .scn file and stops to run, just close without error. After all I make script, that split reference .scn file on small subfiles with 100 lines, run X32GetScene on them and glue result them to one file. Thats works well, but I don't think its a better solution. I think it's better to compile X32GetScene as it should be.

**Comment by pmaillot** [comment]
The X32lib library is in a separate directory in github, as you probably found it. I am not the author of the makefiles files and cannot guaranty their correctness. Maybe X32GetScene should be moved from the MORETARGETS field to the TARGET one, ensuring that an entry for its compile/link is there too.
If the program runs and closes at a certain point, repeatedly, it's probably due to a parsing issue. These files are "old" and have not necessarily been kept up to date with the new parameters appearing as the X32 FW evolved.
I'll run the program on my side and see if changes are necessary, based on a 4.06 FW .scn file.

BR.

**Comment by pmaillot** [comment]
Hello again,
I just ran the program using the version I compile under Eclipse and that is posted on my website, using the emulator (the X32 is not ON at the time). Using my local network.
The command (under Windows) to get a full 4.06 scene I used was:

`more DefScene4.06.scn | ./X32GetScene -i 192.168.0.33 -s sc -n no >myscene.scn
`
note that the "<" shell operator is not active in windows therefore the use of "more" and a pipe

This resulted in a lots of exchanges between the program and the emulator:
```
[....]
X->,   48 B: node~~~~,s~~/ch/17/mix/13 OFF -oo -100 IN/LC 0~~
->X,   28 B: /node~~~,s~~ch/17/mix/14~~~~
X->,   36 B: node~~~~,s~~/ch/17/mix/14 OFF -oo~~~
->X,   28 B: /node~~~,s~~ch/17/mix/15~~~~
X->,   48 B: node~~~~,s~~/ch/17/mix/15 OFF -oo -100 IN/LC 0~~
->X,   28 B: /node~~~,s~~ch/17/mix/16~~~~
X->,   36 B: node~~~~,s~~/ch/17/mix/16 OFF -oo~~~
->X,   24 B: /node~~~,s~~ch/17/grp~~~
X->,   44 B: node~~~~,s~~/ch/17/grp %00000000 %000000~~~~
->X,   28 B: /node~~~,s~~ch/17/automix~~~
X->,   40 B: node~~~~,s~~/ch/17/automix OFF -12.0~~~~
->X,   28 B: /node~~~,s~~ch/18/config~~~~
X->,   40 B: node~~~~,s~~/ch/18/config "" 0 OFF 0~~~~
->X,   24 B: /node~~~,s~~ch/18/delay~
X->,   36 B: node~~~~,s~~/ch/18/delay OFF 0.3~~~~
->X,   28 B: /node~~~,s~~ch/18/preamp~~~~
X->,   52 B: node~~~~,s~~/ch/18/preamp -18.0 OFF OFF 12 20.0~~~~~
->X,   24 B: /node~~~,s~~ch/18/gate~~
X->,   56 B: node~~~~,s~~/ch/18/gate OFF EXP2 -80.0 3.0 0 0.02 5 0~~~
[...]
```


and when the program finished, I had a "myscene.scn" file of **136620** bytes:

```
[....]
#4.0# "sc" "no" %000000000 1 X32GetScene V1.6 (c)2014 Patrick-Gilles Maillot

/config/chlink OFF OFF OFF OFF OFF OFF OFF OFF OFF OFF OFF OFF OFF OFF OFF OFF
/config/auxlink OFF OFF OFF OFF
/config/fxlink OFF OFF OFF OFF
/config/buslink OFF OFF OFF OFF OFF OFF OFF OFF
/config/mtxlink OFF OFF OFF
/config/mute OFF OFF OFF OFF OFF OFF
/config/linkcfg OFF OFF OFF OFF
/config/mono LR+M OFF
/config/solo -oo OFF -18.0 PFL PFL PFL OFF OFF OFF -40 OFF OFF OFF 0.3 OFF OFF OFF
/config/talk OFF INT
/config/talk/A -oo OFF OFF %000000000000000000
/config/talk/B -oo OFF OFF %000000000000000000
/config/osc -oo 20.0 20.0 F1 SINE 0
/config/userrout/out 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
/config/userrout/in 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
/config/routing AN1-8
/config/routing/IN AN1-8 AN1-8 AN1-8 AN1-8 AUX1-4
/config/routing/AES50A AN1-8 AN1-8 AN1-8 AN1-8 AN1-8 AN1-8
/config/routing/AES50B AN1-8 AN1-8 AN1-8 AN1-8 AN1-8 AN1-8
/config/routing/CARD AN1-8 AN1-8 AN1-8 AN1-8
/config/routing/OUT AN1-4 AN1-4 AN5-8 AN5-8
/config/routing/PLAY AN1-8 AN1-8 AN1-8 AN1-8 AUX1-4
/config/userctrl/A OFF
/config/userctrl/A/enc "-" "-" "-" "-"
/config/userctrl/A/btn "-" "-" "-" "-" "-" "-" "-" "-"
/config/userctrl/B OFF
/config/userctrl/B/enc "-" "-" "-" "-"
/config/userctrl/B/btn "-" "-" "-" "-" "-" "-" "-" "-"
/config/userctrl/C OFF
/config/userctrl/C/enc "-" "-" "-" "-"
[...]
```

So all seem OK.

I'll test later with the actual X32 and will re-open the issue if there's new elements.

-P
