### ISSUE TITLE
a few different errors on X32 Emulator v084 mac

### ISSUE THREAD

**Issue by silfversound** [pmaillot/X32-Behringer#32]
1. When starting the application I'm getting this: X32 resource file does not exist, create one with '/shutdown' command. How do I fix this?
2. When connecting from X32 Edit I'm getting this: Error while sending data: No route to host. Do I get this error because I'm running both applications on the same computer?
3. When connecting Mix station on my Tablet I'm getting this: ->X,   16 B: /mtx/03/grp/dca~
zsh: segmentation fault  /Applications/X32/X32_v084_mac_oc

**Comment by pmaillot** [comment]
Hello,
About #2, I don't know what causes this on your mac. Maybe a firewall issue
About #3, the mac version may be too old now for new/updated versions of mixing Station (and even to emulate the X32 latest FW). I don't have access any longer to mac platforms and cannot rebuild the latest version. Maybe you should do that from the source code on Github.

**Comment by rouvenschandl** [comment]
[X32.zip](https://github.com/user-attachments/files/18422203/X32.zip)
I have the latest version for Mac compiled, and that has solved all the problems!

**Comment by pmaillot** [comment]
Oh great!!! You mind sharing the compiled version for other to use too?

Le mer. 15 janv. 2025 à 11:06, Rouven Schandl ***@***.***> a
écrit :

**Comment by pmaillot** [comment]
... or is it already in the link to .zip you sent?  :-)

Le mer. 15 janv. 2025 à 11:06, Rouven Schandl ***@***.***> a
écrit :

**Comment by rouvenschandl** [comment]
Yes, it's in the zip file! 
To use it, you must first run `xattr -d com.apple.quarantine X32`, otherwise macOS will block
