### ISSUE TITLE
not an issue just a question

### ISSUE THREAD

**Issue by NeOdYmS** [pmaillot/X32-Behringer#33]
Hi Pmaillot

congrate for this huge job on this preject !!

i am preparing a touring kit for Live Production/Recording applications
i'm trying to interpolate Live professor cues and Reaper markers using chataigne http://benjamin.kuperberg.fr/chataigne/fr

the idea is to create markers while recording in reaper and changing cues in Live professor
and to going to marker while reading and changing cues

do you know if it's possible to send to reaper an OSC message to create a marker at position with a custom Name  ?

best regards

christophe

**Comment by pmaillot** [comment]
Hello,

 

Last time I checked on the REAPER doc and forums, it was not possible through using OSC. This may have changed … Did you ask/checked with Cokos members?

 

Looking at the default OSC table from REAPER’s latest version, it should be possible… I haven’t check though…

# writing a marker or region time may change its index -- you should use the *ID_ versions below if needed

MARKER_NAME s/marker/@/name

MARKER_NUMBER s/marker/@/number/str

MARKER_TIME f/marker/@/time

REGION_NAME s/region/@/name

REGION_NUMBER s/region/@/number/str

REGION_TIME f/region/@/time

REGION_LENGTH f/region/@/length

LAST_MARKER_NAME s/lastmarker/name

LAST_MARKER_NUMBER s/lastmarker/number/str

LAST_MARKER_TIME f/lastmarker/time

LAST_REGION_NAME s/lastregion/name

LAST_REGION_NUMBER s/lastregion/number/str

LAST_REGION_TIME f/lastregion/time

LAST_REGION_LENGTH f/lastregion/length

 

# these are write-only, ID is the "NUMBER" field from above -- if not found, creates the marker/region

MARKERID_NAME s/marker_id/@/name

MARKERID_TIME f/marker_id/@/time

MARKERID_NUMBER i/marker_id/@/number

REGIONID_NAME s/region_id/@/name

REGIONID_TIME f/region_id/@/time

REGIONID_LENGTH f/region_id/@/length

REGIONID_NUMBER i/region_id/@/number

 

 

-Patrick

 

From: Christophe DAÏRIEN-SERVAIS ***@***.***> 
Sent: Saturday, January 28, 2023 9:42 AM
To: pmaillot/X32-Behringer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pmaillot/X32-Behringer] not an issue just a question (Issue #33)

 

Hi Pmaillot

congrate for this huge job on this preject !!

i am preparing a touring kit for Live Production/Recording applications
i'm trying to interpolate Live professor cues and Reaper markers using chataigne http://benjamin.kuperberg.fr/chataigne/fr

the idea is to create markers while recording in reaper and changing cues in Live professor
and to going to marker while reading and changing cues

do you know if it's possible in reaper to create a marker at positiion with a custom Name thru OSC message ?

best regards

christophe
