### ISSUE TITLE
Question M32R et control distant temps réel

### ISSUE THREAD

**Issue by agfline** [pmaillot/X32-Behringer#35]
Bonjour Patrick,

Bravo quel travail !
Je me permets de vous solliciter pour une question de faisabilité.

Je suis à la recherche d'une console pour une application TV/broadcast mobile et je me demandais s'il était possible avec la M32R, de piloter plusieurs submixes en temps réel (via MidiCC ou autre), de façon transparente et sans interférer avec le travail du mixeur sur le mix principal ?

L'idée serait d'utiliser la console à la fois pour le mix standard du programme, mais également de s'en servir comme d'une petite "matrice d'ordre" qui serait contrôlée par plusieurs personnes en même temps, via plusieurs contrôleurs à base de raspberry pi et uniquement sur des opérations simples (mute/demute de départs d'Aux, réglage de niveaux sur des affectations d'Aux).

J'espère que ma question n'est pas trop confuse et que votre maîtrise de la machine vous permettra de m'apporter un éclairage ;)

Merci encore pour votre travail,

Adrien

**Comment by pmaillot** [comment]
Bonjour,

 

Je vais tenter de répondre au mieux, mais ne prenez pas nécessairement ma réponse comme « golden ». 

 

La M32/X32 (ou même la plus récente WING) sont capables de gérer plusieurs submixes en parallèle… mais avec des limites. Toutes les fonctions sont typiquement assignées à des ressources physiques sur les M32 et X32, plus de flexibilité sur la WING. Cela veut dire qu’une modification de volume, ou de setting utilisant un potar ou un bouton se traduira forcément par une modification sur la chaine audio. Il faut donc être très prudent et quelques fois inventif sur le routing du signal pour éviter ces effets s’ils ne sont pas souhaités, ou accepter de réduire drastiquement le nombre de pistes le permet, si cela est possible.

 

La WING permet beaucoup plus de réglages que la M32, tant au niveau du nombre de pistes mixables (toutes stéréo sur WING) que sur le nombre de réglages (boutons et knobs) annexes qui n’auront pas d’effet sur la chaine audio. Là où la M32 a 12 knobs et 24 boutons dont la plupart associés à des effets ou des fonctions « consoles » [ils peuvent cependant être libérés pour gérer des commandes MIDI], la WING en propose 64 et 96 respectivement, tous libres.

Attention aussi à quelle version de M32 vous pourriez utiliser. Si toutes ont les même capacités logicielles, elles ne proposent pas le même support au niveau ‘surface de travail’, mais cela ne vous affectera pas trop si vous déportez les fonctions recherchées vers des app externes sur Rpi ou autre.

 

Donc la réponse est oui, avec plus de flexibilité et capacités pour la WING, et le point principal est d’évaluer au préalable la faisabilité de votre routing audio avant d’investir, pour être sûr de votre coup.

 

-Patrick

 

From: Adrien Gesta-Fline ***@***.***> 
Sent: Saturday, December 9, 2023 12:45 PM
To: pmaillot/X32-Behringer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pmaillot/X32-Behringer] Question M32R et control distant temps réel (Issue #35)

 

Bonjour Patrick,

Bravo quel travail !
Je me permets de vous solliciter pour une question de faisabilité.

Je suis à la recherche d'une console pour une application TV/broadcast mobile et je me demandais s'il était possible avec la M32, de piloter plusieurs submixes en temps réel (via MidiCC ou autre), de façon transparente et sans interférer avec le travail du mixeur sur le mix principal ?

L'idée serait d'utiliser la console à la fois pour le mix standard du programme, mais également de s'en servir comme d'une petite "matrice d'ordre" qui serait contrôlée par plusieurs personnes en même temps, via plusieurs contrôleurs à base de raspberry pi et uniquement sur des opérations simples (mute/demute, réglage de niveaux).

J'espère que ma question n'est pas trop confuse et que votre maîtrise de la machine vous permettra de m'apporter un éclairage ;)

Merci encore pour votre travail,

Adrien

**Comment by agfline** [comment]
Merci beaucoup Patrick pour votre réponse.

Ca nous aide beaucoup, surtout cette notion de "ressources physiques" qui risque de trop nous limiter dans ce que nous cherchons à réaliser. Peut-être qu'une console plus "récente" (type SQ5 ou même DM3 qui supportent le RTP MIDI / OSC) pourrait être plus appropriée (une de nos contrainte est de rester dans un format 19", donc la WING n'est pas envisageable). De plus, je viens de voir également que la M32 ne disposait pas de custom layer et que les affectations d'entrées se faisaient par bloc de 8, ce qui sera à coup sur problématique pour nous.
Quoi qu'il en soit, je trouve que les fabricants communiquent trop peu sur les capacités de leurs consoles, surtout quand on sort des sentiers battus. En ça, votre dépôt sur github est particulièrement précieux pour des démarches comme la notre !

Merci encore,

Adrien
