### ISSUE TITLE
logic error in fxparse.c 

### ISSUE THREAD

**Issue by kmitch95120** [pmaillot/X32-Behringer#4]
On line 203 of fxparse.c there's a test for PQ5 when the test should be for PQ5S since the "S" is the dual effect with two sets of parameters. 

Here's the diff: 
diff --git a/fxparse.c b/fxparse.c
index c268a1b..b1bab91 100644
--- a/fxparse.c
+++ b/fxparse.c
@@ -200,7 +200,7 @@ int XPQ5_PQ5S(char* buf, int k, int ifx, int PQ5S, int PQ5) {
        list2int(l_qhlfreq, ll_qhlfreq);        // hi freq [1k5, 2k, 3k, 4k, 5k]
        ratio2float(10.);                                       // hi boost [0, 10]
        toggle2int("OFF");                                      // transformer [OFF / ON]
-       if (ifx == PQ5) {
+       if (ifx == PQ5S) {
                toggle2int("OFF");                                      // active [OFF / ON]
                afine2float(-12., 24.);                         // gain [-12, 12]
                list2int(l_qllfreq, ll_qllfreq);        // lo freq [200, 300, 500, 700, 1000]

**Comment by pmaillot** [comment]
Thanks a lot!,

Fixed J

-Patrick

**Comment by kmitch95120** [comment]
Works as expected now.
