### ISSUE TITLE
Integration with video mixer

### ISSUE THREAD

**Issue by sleman** [pmaillot/X32-Behringer#6]
I'm interested in using this great library to interface with our video mixer (BlackMagic ATEM) to get the video mixer to change to a different camera based on the loudest x32 input. This would allow me to auto-mix my event's video based on who is speaking. I see I can use `/meter` to get a list of meters for the various inputs which seems like a good start. Any ideas about how I can best find out which mic input would be chosen in realtime for a period of 1 hour or more?

**Comment by pmaillot** [comment]
Hello,

Looking at some of the descriptions of this "BlackMagic ATEM", there are
audio mixing capabilities that include auto video switching based on audio;
Have you looked into that? It would seem the best option.

Now, if your video mixer does not support audio, I would suggest you test
X32Automix, and see by yourself if this corresponds to your audio
situation. If it does, I can probably provide the last activated audio
channel to an external application if I know what to interface to. You can
also do this yourself or have someone in your staff do this; do no hesitate
to grab the X32Automix source code and work from there.

Hope this helps,
-Patrick

2017-03-13 6:32 GMT+01:00 sleman <notifications@github.com>:

**Comment by sleman** [comment]
Hey Patrick,

Thanks for the quick response. The ATEM is very limited in audio mixing and requires the audio to come with the video over the same cable so won't work for our needs.

X32Automix is a great idea. Would it be possible to have it run and not make any changes to the audio mixer but rather just output the name of the input that it would have selected? So it'd continually output: 

```
Input1
Input2
Input1
```

Or perhaps instead of standard output, it can hit a configurable url and send some JSON data every time there's a change.

**Comment by pmaillot** [comment]
Hello,

 

It’s software so everything is possible J

 

Just a matter of time and programming. The source code is available for such changes, so do not hesitate to grab the file(s) and make/try these changes.

 

Regrads,

-Patrick
