### ISSUE TITLE
Passing IP or network interface to X32

### ISSUE THREAD

**Issue by johnsonbrothers** [pmaillot/X32-Behringer#7]
Om trying to run X32 on my windows10 and X32 is grabbing my virtual network interfave from Virtual Box instead of the IP address from my Wifi or my connected Ethernet cable.
Is there a way to let me decide which IP address X32 will listen on?

**Comment by pmaillot** [comment]
Hello,

 

Check the getmyIP() function; I often have to change the interface name (under linux though) to ensure the program picks up the right interface. On Windows I always use WIFI (no wire interface on my PC, unless I put a $$dongle). The Windows version of the function picks up the first non-null ethernet interface it finds in the list; you can change that.

-Patrick
