### ISSUE TITLE
XAir_Command using wrong data type for meter subscription blob data

### ISSUE THREAD

**Issue by Rippert** [pmaillot/X32-Behringer#8]
When running a meter subscription command such as`/meters ,si /meters/0 8` in XAir_Command, the result comes back as 
`X->,   40 B: /meters/0~~~,b~~8 flts: -00.00 000.00 -00.00 -00.00 000.00 000.00 000.00 000.00`.
This is incorrect. All meter subscriptions commands result in: `Blob contains meter data signed integer 16 bit, resolution 1/256 dB) as single binary blob` on the X-air platform, not floats. This is a difference from the X32 OSC. The code to properly decode this already seems to be in X32_dump.c, starting on line 82 `if(strncmp(buf, "/meters/15", 10) == 0) {`. 
/meters/15 (RTA output) is the one case where the X32 uses short little endian integers in a meter subscription. XAir_Command.c may need to call a custom version of xfdump to properly read meter subscriptions.
I don't have a development environment set up on my mac right now, so I cannot test this myself.

**Comment by pmaillot** [comment]
Thanks for this note/report. I do not have an XR18 to really test. I'll make the chages per you suggestion and you'll be able to test again. give me just a few days; I may be able to achieve this sooner on mac.
-Patrick

**Comment by Rippert** [comment]
Thanks Patrick. I am using a mac to run your utilities. I'm going to finally set up XCode on my Macbook Air in the next couple days. Is there anything I need to set up properly to build your code? I don't see a makefile.

**Comment by pmaillot** [comment]
Actually just fixed it on mac [only for now]. Github updated as well as a compiled /executable MAC version available in the X32mac.zip file available on my website.

**Comment by pmaillot** [comment]
I use Eclipse on my mac. Xcode is kinda painful to me (personal taste). Eclipse lacks a debugger on mac (thanks to Apple thinking they're smarter than the rest of the World), but as I use Mac only to duplicate things I develop on Windows (where there are no issues for debugging) I'm fine.

**Comment by pmaillot** [comment]
Just fixed it (well I hope) Take the code from my website and tell me if it
works as expected. Should be OK :)

2017-12-18 12:28 GMT+01:00 Rippert <notifications@github.com>:

**Comment by Rippert** [comment]
Got it, thanks. I assume it’s the “XR18_Command" executable, it was called XAir_Command when I downloaded it earlier today.

It’s too late here to go over to the studio where my mixer is, but I’ll check it in the morning and get back to you.

Thanks again,
Ted

**Comment by pmaillot** [comment]
Yes. Same thing.

**Comment by Rippert** [comment]
Just tried the new XR18_command. It’s working, but there is extra data coming out.

Send:
/meters ,si /meters/0 13

Receive:
X->,   40 B: /meters/0~~~,b~~16 rta: 
-029.86 -029.86 -020.37 -000.39 -033.45 -033.45 -032.74 -023.57 -115.33 -113.85 -110.74 -109.35 -103.34 -096.81 -080.39 -081.25

 The first 8 values seem correct and change with input, the last 8 values don’t seem to relate to anything and are static. The OSC manual states:
------------
List of Meter IDs:

/meters/0 <chnmeterid>

CHANNEL:

8 channel meters (pre-fader l/r, gate and comp gain reduction, post-fader l/r meters, gate key, comp key)

-> returns one integer size value and 8 short signed integer values (16 bit) as single binary blob 

-------------

I see the same thing when looking at the RTA output from /meters/4, 100 dynamic values, followed by 100 static values, mostly zeros.

So it’s obviously not exactly like the X32 RTA blob, but close enough that the correct values seem to come out, just with some extras. I can’t tell from the code exactly what is wrong. It’s actually usable as is, but if you can fix the extra output, it would be perfect (at least the meter subscription part - I’ve only tested a few other commands)

Thanks,
Ted

**Comment by Rippert** [comment]
Sorry, I can tell whats wrong with the code, line 205 of XAir_Command.c:
n = endian.i1 * 2;
should be:
n = endian.i1;

Seems pretty likely.

Thanks again,
Ted

**Comment by kmitch95120** [comment]
Hi Ted, 

My code is a fork of Patrick's repo which is probably how you ended up here.  XAir_Command has diverged from XR18_Command a bit so I think Patrick made the change to an older version of the code. I'll sync up with him and get it straight. 

Thanks,
Ken

**Comment by pmaillot** [comment]
Hello,

I was quickly looking at this this morning and thought the issue could come
from there. Again, not havin an XR to visualize the results of a command is
not helping. I'm kinda blind here. I'll make the change in the XR18_command
code, now that the dump function is included in the main source, so you can
try quickly.
-Patrick

2017-12-19 1:13 GMT+01:00 kmitch95120 <notifications@github.com>:

**Comment by pmaillot** [comment]
Done, if you want to test it.
-Patrick

2017-12-19 8:20 GMT+01:00 Patrick-Gilles Maillot <patrick.maillot@gmail.com>
:

**Comment by Rippert** [comment]
Just tested it. Looks like it’s working properly now, values look correct and no extra numbers in the readout.

Thanks again,
Ted

**Comment by pmaillot** [comment]
Good!; Thanks a lot for reporting the issue.
-Patrick

2017-12-19 8:42 GMT+01:00 Rippert <notifications@github.com>:

> Just tested it. Looks like it’s working properly now, values look correct
> and no extra numbers in the readout.
>
> Thanks again,
> Ted
>
> > On Dec 19, 2017, at 12:25 AM, Patrick-Gilles Maillot <
